### ISSUE TITLE
Crash while pressing “submit” on a keyboard of a TextField

### ISSUE THREAD

**Issue by rk-ib** [rickclephas/KMM-ViewModel#17] opened 2023-02-17 08:27 UTC
**Issue:**

I get a crash while pressing “submit” on keyboard of a TextField, that uses a published var from the viewModel.

“Thread 1: Simultaneous accesses to 0x600002e2b358, but modification requires exclusive access” on ObservableViewModel:25

**Setup:**

iOS viewModel is extending shared.ViewModel

on the viewModel side, the Published var used as input text binding for Textfield is defined like this:

```
@Published var username: String = "" {
        didSet {
            isUsernameValid = validateUsername(email: username)

            validatePasswordLogin()
        }
    }
```
ViewModel var inside the View is annotated with @StateViewModel

```
struct LoginView: View {
    @StateViewModel var viewModel: LoginViewModel

    var body: some View {
        TextField(text: $viewModel.username, label: {
            Text("test")
        })
    }
}
```
**Proposed fix:**

Since simultaneous access could be avoided by doing the writing async, i tried the following and it fixed the crash - no idea if its a worthy solution here.

ObservableViewModel:35 - the function that does the setting of keypath, i wrapped that line inside a DispatchQueue.main.async

```
     public func set<T>(_ keyPath: WritableKeyPath<ViewModel, T>, to newValue: T) {
        DispatchQueue.main.async {
            self._viewModel[keyPath: keyPath] = newValue
        }
     }
```
 
**Versions on the iOS side:**

  pod 'KMMViewModelCore', :git => 'https://github.com/rickclephas/KMM-ViewModel.git', :commit => '047d8c597715d57be2951d121f686c2886e5a39f'
  pod 'KMMViewModelCoreObjC', :git => 'https://github.com/rickclephas/KMM-ViewModel.git', :commit => '047d8c597715d57be2951d121f686c2886e5a39f'
  pod 'KMMViewModelSwiftUI', :git => 'https://github.com/rickclephas/KMM-ViewModel.git', :commit => '047d8c597715d57be2951d121f686c2886e5a39f'

**Comment by rickclephas** [comment] 2023-04-16 19:57
Hi, sorry for the delay!

Was able to reproduce this and it was indeed caused by `_viewModel[keyPath: keyPath] = newValue`.
However since the viewmodels are all classes we don't actual need a mutable variable for the keyPath.

Fix has been released in [v1.0.0-ALPHA-6](https://github.com/rickclephas/KMM-ViewModel/releases/tag/v1.0.0-ALPHA-6)!

**Closed by rickclephas** 2023-04-16 19:57 UTC
